#!/bin/bash
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# This script collects the generated ini-file parts and combines them into single ini-files (one for each component artefact)
#

# create subfolder combined-ini-files (if not yet created)
echo "create subfolder src-gen/combined-ini-files"
mkdir -p src-gen/combined-ini-files

# clean-up old combined-ini-files before they are generated again
echo "clean-up src-gen/combined-ini-files subfolder"
rm src-gen/combined-ini-files/*.ini

# create ini-file ComponentPlayerStageSimulator.ini
echo "create ini-file ComponentPlayerStageSimulator.ini"
cp src-gen/system/ComponentPlayerStageSimulator.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentPlayerStageSimulator.ini ]; then
  cat src-gen/params/ComponentPlayerStageSimulator.ini >> src-gen/combined-ini-files/ComponentPlayerStageSimulator.ini
fi

# create ini-file SmartCdlServer.ini
echo "create ini-file SmartCdlServer.ini"
cp src-gen/system/SmartCdlServer.ini src-gen/combined-ini-files/
if [ -f src-gen/params/SmartCdlServer.ini ]; then
  cat src-gen/params/SmartCdlServer.ini >> src-gen/combined-ini-files/SmartCdlServer.ini
fi

# create ini-file SmartMapperGridMap.ini
echo "create ini-file SmartMapperGridMap.ini"
cp src-gen/system/SmartMapperGridMap.ini src-gen/combined-ini-files/
if [ -f src-gen/params/SmartMapperGridMap.ini ]; then
  cat src-gen/params/SmartMapperGridMap.ini >> src-gen/combined-ini-files/SmartMapperGridMap.ini
fi

# create ini-file SmartPlannerBreadthFirstSearch.ini
echo "create ini-file SmartPlannerBreadthFirstSearch.ini"
cp src-gen/system/SmartPlannerBreadthFirstSearch.ini src-gen/combined-ini-files/
if [ -f src-gen/params/SmartPlannerBreadthFirstSearch.ini ]; then
  cat src-gen/params/SmartPlannerBreadthFirstSearch.ini >> src-gen/combined-ini-files/SmartPlannerBreadthFirstSearch.ini
fi

# create ini-file SmartRobotConsole.ini
echo "create ini-file SmartRobotConsole.ini"
cp src-gen/system/SmartRobotConsole.ini src-gen/combined-ini-files/
if [ -f src-gen/params/SmartRobotConsole.ini ]; then
  cat src-gen/params/SmartRobotConsole.ini >> src-gen/combined-ini-files/SmartRobotConsole.ini
fi

