#!/bin/bash
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# This script collects the generated ini-file parts and combines them into single ini-files (one for each component artefact)
#

# create subfolder combined-ini-files (if not yet created)
echo "create subfolder src-gen/combined-ini-files"
mkdir -p src-gen/combined-ini-files

# clean-up old combined-ini-files before they are generated again
echo "clean-up src-gen/combined-ini-files subfolder"
rm src-gen/combined-ini-files/*.ini

# create ini-file ComponentGMapping.ini
echo "create ini-file ComponentGMapping.ini"
cp src-gen/system/ComponentGMapping.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentGMapping.ini ]; then
  cat src-gen/params/ComponentGMapping.ini >> src-gen/combined-ini-files/ComponentGMapping.ini
fi

# create ini-file ComponentGMapping_rs.ini
echo "create ini-file ComponentGMapping_rs.ini"
cp src-gen/system/ComponentGMapping_rs.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentGMapping_rs.ini ]; then
  cat src-gen/params/ComponentGMapping_rs.ini >> src-gen/combined-ini-files/ComponentGMapping_rs.ini
fi

# create ini-file ComponentKB.ini
echo "create ini-file ComponentKB.ini"
cp src-gen/system/ComponentKB.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentKB.ini ]; then
  cat src-gen/params/ComponentKB.ini >> src-gen/combined-ini-files/ComponentKB.ini
fi

# create ini-file ComponentLaserFromRGBDServer.ini
echo "create ini-file ComponentLaserFromRGBDServer.ini"
cp src-gen/system/ComponentLaserFromRGBDServer.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentLaserFromRGBDServer.ini ]; then
  cat src-gen/params/ComponentLaserFromRGBDServer.ini >> src-gen/combined-ini-files/ComponentLaserFromRGBDServer.ini
fi

# create ini-file ComponentRealSenseV2Server.ini
echo "create ini-file ComponentRealSenseV2Server.ini"
cp src-gen/system/ComponentRealSenseV2Server.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentRealSenseV2Server.ini ]; then
  cat src-gen/params/ComponentRealSenseV2Server.ini >> src-gen/combined-ini-files/ComponentRealSenseV2Server.ini
fi

# create ini-file ComponentRobotinoBaseServer.ini
echo "create ini-file ComponentRobotinoBaseServer.ini"
cp src-gen/system/ComponentRobotinoBaseServer.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentRobotinoBaseServer.ini ]; then
  cat src-gen/params/ComponentRobotinoBaseServer.ini >> src-gen/combined-ini-files/ComponentRobotinoBaseServer.ini
fi

# create ini-file ComponentRobotinoLaserServer.ini
echo "create ini-file ComponentRobotinoLaserServer.ini"
cp src-gen/system/ComponentRobotinoLaserServer.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentRobotinoLaserServer.ini ]; then
  cat src-gen/params/ComponentRobotinoLaserServer.ini >> src-gen/combined-ini-files/ComponentRobotinoLaserServer.ini
fi

# create ini-file ComponentTCLSequencer.ini
echo "create ini-file ComponentTCLSequencer.ini"
cp src-gen/system/ComponentTCLSequencer.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentTCLSequencer.ini ]; then
  cat src-gen/params/ComponentTCLSequencer.ini >> src-gen/combined-ini-files/ComponentTCLSequencer.ini
fi

# create ini-file ComponentVisualization.ini
echo "create ini-file ComponentVisualization.ini"
cp src-gen/system/ComponentVisualization.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentVisualization.ini ]; then
  cat src-gen/params/ComponentVisualization.ini >> src-gen/combined-ini-files/ComponentVisualization.ini
fi

# create ini-file ComponentVisualization2.ini
echo "create ini-file ComponentVisualization2.ini"
cp src-gen/system/ComponentVisualization2.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentVisualization2.ini ]; then
  cat src-gen/params/ComponentVisualization2.ini >> src-gen/combined-ini-files/ComponentVisualization2.ini
fi

# create ini-file SmartRobotConsole.ini
echo "create ini-file SmartRobotConsole.ini"
cp src-gen/system/SmartRobotConsole.ini src-gen/combined-ini-files/
if [ -f src-gen/params/SmartRobotConsole.ini ]; then
  cat src-gen/params/SmartRobotConsole.ini >> src-gen/combined-ini-files/SmartRobotConsole.ini
fi

