#!/bin/sh
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# start script for device c26_25_robotino3


PID_XTERM="/var/tmp/start-c26_25_robotino3-xterms.pid"
PID_COMPONENT_NAMES="/var/tmp/start-c26_25_robotino3-component-names.pid"

SCRIPT_DIR=`pwd`
SCRIPT_NAME=start-c26_25_robotino3.sh

export SMART_ROOT_DEPLOYMENT=$SCRIPT_DIR

#######
## case
case "$1" in
	    
	    
#########################################################################################
## start
start)

true > $PID_XTERM
true > $PID_COMPONENT_NAMES

echo "Starting scenario..."
date -R

# CONFIGURE NAMING SERVICE
	export SMART_NS_ADDR=c26-25-robotino3:20002

echo "Stopping Naming Service..."
killall AceSmartSoftNamingService &
test -e SMART_NAMES && rm -f SMART_NAMES
sleep 1
echo Starting Naming Service...
rm -f AceSmartSoftNamingService.log
xterm -l -lf AceSmartSoftNamingService.log -title "AceSmartSoftNamingService" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; ./NamingService/AceSmartSoftNamingService --ns-port 20002 --ns-dir ./ --ns-file SMART_NAMES --filename=ns_config.ini; echo; echo; echo 'Naming Service exited'; /bin/bash" &
echo $! >> $PID_XTERM
echo AceSmartSoftNamingService >> $PID_COMPONENT_NAMES
sleep 1

## start components
export SMART_IP=c26-25-robotino3
echo "starting components..."

# Component instance ComponentGMapping
echo
echo "############################################"
echo "## Starting component instance ComponentGMapping"
cd $SCRIPT_DIR
echo "executing startstop-hooks-ComponentGMapping.sh (errors might be ignored)"
bash startstop-hooks-ComponentGMapping.sh pre-start
cd $SCRIPT_DIR/ComponentGMapping_data
rm -f "../ComponentGMapping.log"
xterm -l -lf "../ComponentGMapping.log" -title "ComponentGMapping@c26_25_robotino3 Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/ComponentGMapping -filename=$SCRIPT_DIR/ComponentGMapping.ini; echo; echo; echo 'ComponentGMapping exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo ComponentGMapping >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-ComponentGMapping.sh post-start
echo -e "\n\n\n"

# Component instance ComponentGMapping_rs
echo
echo "############################################"
echo "## Starting component instance ComponentGMapping_rs"
cd $SCRIPT_DIR
echo "executing startstop-hooks-ComponentGMapping_rs.sh (errors might be ignored)"
bash startstop-hooks-ComponentGMapping_rs.sh pre-start
cd $SCRIPT_DIR/ComponentGMapping_rs_data
rm -f "../ComponentGMapping_rs.log"
xterm -l -lf "../ComponentGMapping_rs.log" -title "ComponentGMapping_rs@c26_25_robotino3 Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/ComponentGMapping -filename=$SCRIPT_DIR/ComponentGMapping_rs.ini; echo; echo; echo 'ComponentGMapping_rs exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo ComponentGMapping >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-ComponentGMapping_rs.sh post-start
echo -e "\n\n\n"

# Component instance ComponentKB
echo
echo "############################################"
echo "## Starting component instance ComponentKB"
cd $SCRIPT_DIR
echo "executing startstop-hooks-ComponentKB.sh (errors might be ignored)"
bash startstop-hooks-ComponentKB.sh pre-start
cd $SCRIPT_DIR/ComponentKB_data
rm -f "../ComponentKB.log"
xterm -l -lf "../ComponentKB.log" -title "ComponentKB@c26_25_robotino3 Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/ComponentKB -filename=$SCRIPT_DIR/ComponentKB.ini; echo; echo; echo 'ComponentKB exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo ComponentKB >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-ComponentKB.sh post-start
echo -e "\n\n\n"

# Component instance ComponentLaserFromRGBDServer
echo
echo "############################################"
echo "## Starting component instance ComponentLaserFromRGBDServer"
cd $SCRIPT_DIR
echo "executing startstop-hooks-ComponentLaserFromRGBDServer.sh (errors might be ignored)"
bash startstop-hooks-ComponentLaserFromRGBDServer.sh pre-start
cd $SCRIPT_DIR/ComponentLaserFromRGBDServer_data
rm -f "../ComponentLaserFromRGBDServer.log"
xterm -l -lf "../ComponentLaserFromRGBDServer.log" -title "ComponentLaserFromRGBDServer@c26_25_robotino3 Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/ComponentLaserFromRGBDServer -filename=$SCRIPT_DIR/ComponentLaserFromRGBDServer.ini; echo; echo; echo 'ComponentLaserFromRGBDServer exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo ComponentLaserFromRGBDServer >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-ComponentLaserFromRGBDServer.sh post-start
echo -e "\n\n\n"

# Component instance ComponentRealSenseV2Server
echo
echo "############################################"
echo "## Starting component instance ComponentRealSenseV2Server"
cd $SCRIPT_DIR
echo "executing startstop-hooks-ComponentRealSenseV2Server.sh (errors might be ignored)"
bash startstop-hooks-ComponentRealSenseV2Server.sh pre-start
cd $SCRIPT_DIR/ComponentRealSenseV2Server_data
rm -f "../ComponentRealSenseV2Server.log"
xterm -l -lf "../ComponentRealSenseV2Server.log" -title "ComponentRealSenseV2Server@c26_25_robotino3 Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/ComponentRealSenseV2Server -filename=$SCRIPT_DIR/ComponentRealSenseV2Server.ini; echo; echo; echo 'ComponentRealSenseV2Server exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo ComponentRealSenseV2Server >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-ComponentRealSenseV2Server.sh post-start
echo -e "\n\n\n"

# Component instance ComponentRobotinoBaseServer
echo
echo "############################################"
echo "## Starting component instance ComponentRobotinoBaseServer"
cd $SCRIPT_DIR
echo "executing startstop-hooks-ComponentRobotinoBaseServer.sh (errors might be ignored)"
bash startstop-hooks-ComponentRobotinoBaseServer.sh pre-start
cd $SCRIPT_DIR/ComponentRobotinoBaseServer_data
rm -f "../ComponentRobotinoBaseServer.log"
xterm -l -lf "../ComponentRobotinoBaseServer.log" -title "ComponentRobotinoBaseServer@c26_25_robotino3 Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/ComponentRobotinoBaseServer -filename=$SCRIPT_DIR/ComponentRobotinoBaseServer.ini; echo; echo; echo 'ComponentRobotinoBaseServer exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo ComponentRobotinoBaseServer >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-ComponentRobotinoBaseServer.sh post-start
echo -e "\n\n\n"

# Component instance ComponentRobotinoLaserServer
echo
echo "############################################"
echo "## Starting component instance ComponentRobotinoLaserServer"
cd $SCRIPT_DIR
echo "executing startstop-hooks-ComponentRobotinoLaserServer.sh (errors might be ignored)"
bash startstop-hooks-ComponentRobotinoLaserServer.sh pre-start
cd $SCRIPT_DIR/ComponentRobotinoLaserServer_data
rm -f "../ComponentRobotinoLaserServer.log"
xterm -l -lf "../ComponentRobotinoLaserServer.log" -title "ComponentRobotinoLaserServer@c26_25_robotino3 Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/ComponentRobotinoLaserServer -filename=$SCRIPT_DIR/ComponentRobotinoLaserServer.ini; echo; echo; echo 'ComponentRobotinoLaserServer exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo ComponentRobotinoLaserServer >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-ComponentRobotinoLaserServer.sh post-start
echo -e "\n\n\n"

# Component instance ComponentTCLSequencer
echo
echo "############################################"
echo "## Starting component instance ComponentTCLSequencer"
cd $SCRIPT_DIR
echo "executing startstop-hooks-ComponentTCLSequencer.sh (errors might be ignored)"
bash startstop-hooks-ComponentTCLSequencer.sh pre-start
cd $SCRIPT_DIR/ComponentTCLSequencer_data
rm -f "../ComponentTCLSequencer.log"
xterm -l -lf "../ComponentTCLSequencer.log" -title "ComponentTCLSequencer@c26_25_robotino3 Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/ComponentTCLSequencer -filename=$SCRIPT_DIR/ComponentTCLSequencer.ini; echo; echo; echo 'ComponentTCLSequencer exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo ComponentTCLSequencer >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-ComponentTCLSequencer.sh post-start
echo -e "\n\n\n"

# Component instance ComponentVisualization
echo
echo "############################################"
echo "## Starting component instance ComponentVisualization"
cd $SCRIPT_DIR
echo "executing startstop-hooks-ComponentVisualization.sh (errors might be ignored)"
bash startstop-hooks-ComponentVisualization.sh pre-start
cd $SCRIPT_DIR/ComponentVisualization_data
rm -f "../ComponentVisualization.log"
xterm -l -lf "../ComponentVisualization.log" -title "ComponentVisualization@c26_25_robotino3 Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/ComponentVisualization -filename=$SCRIPT_DIR/ComponentVisualization.ini; echo; echo; echo 'ComponentVisualization exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo ComponentVisualization >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-ComponentVisualization.sh post-start
echo -e "\n\n\n"

# Component instance ComponentVisualization2
echo
echo "############################################"
echo "## Starting component instance ComponentVisualization2"
cd $SCRIPT_DIR
echo "executing startstop-hooks-ComponentVisualization2.sh (errors might be ignored)"
bash startstop-hooks-ComponentVisualization2.sh pre-start
cd $SCRIPT_DIR/ComponentVisualization2_data
rm -f "../ComponentVisualization2.log"
xterm -l -lf "../ComponentVisualization2.log" -title "ComponentVisualization2@c26_25_robotino3 Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/ComponentVisualization -filename=$SCRIPT_DIR/ComponentVisualization2.ini; echo; echo; echo 'ComponentVisualization2 exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo ComponentVisualization >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-ComponentVisualization2.sh post-start
echo -e "\n\n\n"

# Component instance SmartRobotConsole
echo
echo "############################################"
echo "## Starting component instance SmartRobotConsole"
cd $SCRIPT_DIR
echo "executing startstop-hooks-SmartRobotConsole.sh (errors might be ignored)"
bash startstop-hooks-SmartRobotConsole.sh pre-start
cd $SCRIPT_DIR/SmartRobotConsole_data
rm -f "../SmartRobotConsole.log"
xterm -l -lf "../SmartRobotConsole.log" -title "SmartRobotConsole@c26_25_robotino3 Component" -hold -e "export LD_LIBRARY_PATH=$SCRIPT_DIR:\$LD_LIBRARY_PATH; $SCRIPT_DIR/SmartRobotConsole -filename=$SCRIPT_DIR/SmartRobotConsole.ini; echo; echo; echo 'SmartRobotConsole exited.'; echo; /bin/bash --login" &
echo $! >> $PID_XTERM
echo SmartRobotConsole >> $PID_COMPONENT_NAMES
cd $SCRIPT_DIR
bash startstop-hooks-SmartRobotConsole.sh post-start
echo -e "\n\n\n"


cd $SCRIPT_DIR

;; ## start


#########################################################################################
## stop
stop)
cd $SCRIPT_DIR
bash startstop-hooks-ComponentGMapping.sh pre-stop
bash startstop-hooks-ComponentGMapping_rs.sh pre-stop
bash startstop-hooks-ComponentKB.sh pre-stop
bash startstop-hooks-ComponentLaserFromRGBDServer.sh pre-stop
bash startstop-hooks-ComponentRealSenseV2Server.sh pre-stop
bash startstop-hooks-ComponentRobotinoBaseServer.sh pre-stop
bash startstop-hooks-ComponentRobotinoLaserServer.sh pre-stop
bash startstop-hooks-ComponentTCLSequencer.sh pre-stop
bash startstop-hooks-ComponentVisualization.sh pre-stop
bash startstop-hooks-ComponentVisualization2.sh pre-stop
bash startstop-hooks-SmartRobotConsole.sh pre-stop

echo "kill all components..."

for I in `cat $PID_COMPONENT_NAMES`; do
        echo $I
        killall -2 $I
done
rm $PID_COMPONENT_NAMES

sleep 3

for I in `cat $PID_XTERM`; do
        echo $I
        kill -2 $I
done
rm $PID_XTERM



test -e SMART_NAMES && rm -f SMART_NAMES

bash startstop-hooks-ComponentGMapping.sh post-stop
bash startstop-hooks-ComponentGMapping_rs.sh post-stop
bash startstop-hooks-ComponentKB.sh post-stop
bash startstop-hooks-ComponentLaserFromRGBDServer.sh post-stop
bash startstop-hooks-ComponentRealSenseV2Server.sh post-stop
bash startstop-hooks-ComponentRobotinoBaseServer.sh post-stop
bash startstop-hooks-ComponentRobotinoLaserServer.sh post-stop
bash startstop-hooks-ComponentTCLSequencer.sh post-stop
bash startstop-hooks-ComponentVisualization.sh post-stop
bash startstop-hooks-ComponentVisualization2.sh post-stop
bash startstop-hooks-SmartRobotConsole.sh post-stop


# collect log files
ls -l *.log && (
	pwd
	tar czvf c26_25_robotino3-logs-$(date +"%Y%m%d%H%M").tar.gz *.log
	rm *.log
)

;; ## stop



#########################################################################################
## menu

menu-start)
	bash $SCRIPT_NAME start
	cd $SCRIPT_DIR
	bash $SCRIPT_NAME menu
;;

menu-stop)
	bash $SCRIPT_NAME stop
	cd $SCRIPT_DIR
	bash $SCRIPT_NAME menu
;;

menu-tile)
	bash tiler.sh
	cd $SCRIPT_DIR
	bash $SCRIPT_NAME menu
;;

menu)

#wmctrl -r :ACTIVE: -b add,above
ACTION=$(whiptail --title "Scenario Control" --menu "Choose an option" 12 35 4 "menu-start" "Start Scenario" "menu-stop" "Stop Scenario" "menu-tile" "Arrange terminals" "quit" "Quit to console" 3>&1 1>&2 2>&3)
#whiptail --title "Scenario Control" --menu "Choose an option" 10 30 3 "menu-start" "Start Scenario" "menu-stop" "Stop Scenario" "quit" "Quit to console" 2>/tmp/whip
#ACTION=`cat /tmp/whip`

cd $SCRIPT_DIR
bash $SCRIPT_NAME $ACTION

;; ## menu

quit)
	bash $SCRIPT_NAME stop
;;
		
		
#########################################################################################
## default
*)
echo "No such parameter: $1"
echo "Usage: $SCRIPT_NAME {start|stop|menu-start|menu-stop|menu}"
exit 1
;;

esac
