#!/bin/bash
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# This script collects the generated ini-file parts and combines them into single ini-files (one for each component artefact)
#

# create subfolder combined-ini-files (if not yet created)
echo "create subfolder src-gen/combined-ini-files"
mkdir -p src-gen/combined-ini-files

# clean-up old combined-ini-files before they are generated again
echo "clean-up src-gen/combined-ini-files subfolder"
rm src-gen/combined-ini-files/*.ini

# create ini-file ComponentKB_11.ini
echo "create ini-file ComponentKB_11.ini"
cp src-gen/system/ComponentKB_11.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentKB_11.ini ]; then
  cat src-gen/params/ComponentKB_11.ini >> src-gen/combined-ini-files/ComponentKB_11.ini
fi

# create ini-file ComponentLaserLMS1xx.ini
echo "create ini-file ComponentLaserLMS1xx.ini"
cp src-gen/system/ComponentLaserLMS1xx.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentLaserLMS1xx.ini ]; then
  cat src-gen/params/ComponentLaserLMS1xx.ini >> src-gen/combined-ini-files/ComponentLaserLMS1xx.ini
fi

# create ini-file ComponentRobotinoBaseServer.ini
echo "create ini-file ComponentRobotinoBaseServer.ini"
cp src-gen/system/ComponentRobotinoBaseServer.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentRobotinoBaseServer.ini ]; then
  cat src-gen/params/ComponentRobotinoBaseServer.ini >> src-gen/combined-ini-files/ComponentRobotinoBaseServer.ini
fi

# create ini-file ComponentTCLSequencer.ini
echo "create ini-file ComponentTCLSequencer.ini"
cp src-gen/system/ComponentTCLSequencer.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentTCLSequencer.ini ]; then
  cat src-gen/params/ComponentTCLSequencer.ini >> src-gen/combined-ini-files/ComponentTCLSequencer.ini
fi

# create ini-file SmartAmcl.ini
echo "create ini-file SmartAmcl.ini"
cp src-gen/system/SmartAmcl.ini src-gen/combined-ini-files/
if [ -f src-gen/params/SmartAmcl.ini ]; then
  cat src-gen/params/SmartAmcl.ini >> src-gen/combined-ini-files/SmartAmcl.ini
fi

# create ini-file SmartCdlServer1.ini
echo "create ini-file SmartCdlServer1.ini"
cp src-gen/system/SmartCdlServer1.ini src-gen/combined-ini-files/
if [ -f src-gen/params/SmartCdlServer1.ini ]; then
  cat src-gen/params/SmartCdlServer1.ini >> src-gen/combined-ini-files/SmartCdlServer1.ini
fi

# create ini-file SmartJoystickNavigation.ini
echo "create ini-file SmartJoystickNavigation.ini"
cp src-gen/system/SmartJoystickNavigation.ini src-gen/combined-ini-files/
if [ -f src-gen/params/SmartJoystickNavigation.ini ]; then
  cat src-gen/params/SmartJoystickNavigation.ini >> src-gen/combined-ini-files/SmartJoystickNavigation.ini
fi

# create ini-file SmartJoystickServer.ini
echo "create ini-file SmartJoystickServer.ini"
cp src-gen/system/SmartJoystickServer.ini src-gen/combined-ini-files/
if [ -f src-gen/params/SmartJoystickServer.ini ]; then
  cat src-gen/params/SmartJoystickServer.ini >> src-gen/combined-ini-files/SmartJoystickServer.ini
fi

# create ini-file SmartMapperGridMap1.ini
echo "create ini-file SmartMapperGridMap1.ini"
cp src-gen/system/SmartMapperGridMap1.ini src-gen/combined-ini-files/
if [ -f src-gen/params/SmartMapperGridMap1.ini ]; then
  cat src-gen/params/SmartMapperGridMap1.ini >> src-gen/combined-ini-files/SmartMapperGridMap1.ini
fi

# create ini-file SmartPlannerBreadthFirstSearch1.ini
echo "create ini-file SmartPlannerBreadthFirstSearch1.ini"
cp src-gen/system/SmartPlannerBreadthFirstSearch1.ini src-gen/combined-ini-files/
if [ -f src-gen/params/SmartPlannerBreadthFirstSearch1.ini ]; then
  cat src-gen/params/SmartPlannerBreadthFirstSearch1.ini >> src-gen/combined-ini-files/SmartPlannerBreadthFirstSearch1.ini
fi

