#!/bin/bash
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# This script collects the generated ini-file parts and combines them into single ini-files (one for each component artefact)
#

# create subfolder combined-ini-files (if not yet created)
echo "create subfolder src-gen/combined-ini-files"
mkdir -p src-gen/combined-ini-files

# clean-up old combined-ini-files before they are generated again
echo "clean-up src-gen/combined-ini-files subfolder"
rm src-gen/combined-ini-files/*.ini

# create ini-file ComponentTTS.ini
echo "create ini-file ComponentTTS.ini"
cp src-gen/system/ComponentTTS.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentTTS.ini ]; then
  cat src-gen/params/ComponentTTS.ini >> src-gen/combined-ini-files/ComponentTTS.ini
fi

# create ini-file ComponentTTSClient.ini
echo "create ini-file ComponentTTSClient.ini"
cp src-gen/system/ComponentTTSClient.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentTTSClient.ini ]; then
  cat src-gen/params/ComponentTTSClient.ini >> src-gen/combined-ini-files/ComponentTTSClient.ini
fi

